begin;

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(trim(name)) between 1 and 40),
  created_at timestamp with time zone not null default now()
);

insert into public.profiles (name)
select 'Tobias'
where not exists (select 1 from public.profiles);

alter table public.program_exercises
  add column if not exists profile_id bigint references public.profiles(id) on delete cascade;

alter table public.workouts
  add column if not exists profile_id bigint references public.profiles(id) on delete cascade;

update public.program_exercises
set profile_id = (select id from public.profiles order by id limit 1)
where profile_id is null;

update public.workouts
set profile_id = (select id from public.profiles order by id limit 1)
where profile_id is null;

alter table public.program_exercises alter column profile_id set not null;
alter table public.workouts alter column profile_id set not null;

alter table public.program_exercises
  drop constraint if exists program_exercises_day_name_exercise_id_key;

create unique index if not exists program_exercises_profile_day_exercise_idx
  on public.program_exercises(profile_id, day_name, exercise_id);

create index if not exists workouts_profile_date_idx
  on public.workouts(profile_id, workout_date desc, id desc);

create index if not exists program_exercises_profile_day_idx
  on public.program_exercises(profile_id, day_name, sort_order);

create or replace function public.save_workout_atomic(
  p_profile_id bigint,
  p_workout_date date,
  p_day_name text,
  p_notes text,
  p_sets jsonb
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_workout_id bigint;
begin
  if not exists (select 1 from public.profiles where id = p_profile_id) then
    raise exception 'Profile not found';
  end if;

  if p_day_name not in ('Pass 1', 'Pass 2', 'Pass 3', 'Pass 4') then
    raise exception 'Invalid workout day';
  end if;

  if jsonb_typeof(p_sets) <> 'array' or jsonb_array_length(p_sets) = 0 then
    raise exception 'At least one set is required';
  end if;

  insert into public.workouts(profile_id, workout_date, day_name, notes)
  values (p_profile_id, p_workout_date, p_day_name, coalesce(p_notes, ''))
  returning id into new_workout_id;

  insert into public.workout_sets
    (workout_id, exercise_id, set_no, reps, weight_kg, is_pr)
  select
    new_workout_id,
    (item->>'exercise_id')::bigint,
    (item->>'set_no')::integer,
    (item->>'reps')::integer,
    (item->>'weight_kg')::numeric,
    coalesce((item->>'is_pr')::boolean, false)
  from jsonb_array_elements(p_sets) as item;

  return new_workout_id;
end;
$$;

-- The weekly GitHub Action may call this without receiving access to user data.
create or replace function public.keepalive()
returns boolean
language sql
security definer
set search_path = public
as $$ select true $$;

alter table public.profiles enable row level security;
alter table public.exercises enable row level security;
alter table public.program_exercises enable row level security;
alter table public.workouts enable row level security;
alter table public.workout_sets enable row level security;

revoke all on table public.profiles from anon, authenticated;
revoke all on table public.exercises from anon, authenticated;
revoke all on table public.program_exercises from anon, authenticated;
revoke all on table public.workouts from anon, authenticated;
revoke all on table public.workout_sets from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
revoke all on function public.save_workout_atomic(bigint, date, text, text, jsonb) from public, anon, authenticated;
revoke all on function public.keepalive() from public, authenticated;
grant execute on function public.keepalive() to anon;

grant all on table public.profiles to service_role;
grant all on table public.exercises to service_role;
grant all on table public.program_exercises to service_role;
grant all on table public.workouts to service_role;
grant all on table public.workout_sets to service_role;
grant usage, select on all sequences in schema public to service_role;
grant execute on function public.save_workout_atomic(bigint, date, text, text, jsonb) to service_role;

commit;
