create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table if not exists public.program_exercises (
  id bigint generated by default as identity primary key,
  day_name text not null,
  exercise_id bigint not null references public.exercises(id) on delete cascade,
  sort_order integer not null default 1,
  sets integer not null,
  rep_min integer not null,
  rep_max integer not null,
  active boolean not null default true,
  unique(day_name, exercise_id)
);

create table if not exists public.workouts (
  id bigint generated by default as identity primary key,
  workout_date date not null,
  day_name text not null,
  notes text not null default '',
  created_at timestamp with time zone not null default now()
);

create table if not exists public.workout_sets (
  id bigint generated by default as identity primary key,
  workout_id bigint not null references public.workouts(id) on delete cascade,
  exercise_id bigint not null references public.exercises(id) on delete cascade,
  set_no integer not null,
  reps integer not null,
  weight_kg numeric not null,
  is_pr boolean not null default false
);

create index if not exists workout_sets_workout_id_idx on public.workout_sets(workout_id);
create index if not exists workout_sets_exercise_id_idx on public.workout_sets(exercise_id);
create index if not exists workouts_workout_date_idx on public.workouts(workout_date desc);

-- Appen använder en enkel PIN i Streamlit ovanpå dessa tabeller.
-- Lämna RLS avstängt för enklast privat användning bakom PIN.
