[supabase]
url = "https://psnzaxbglywboyznayik.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzbnpheGJnbHl3Ym95em5heWlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjA1MjEsImV4cCI6MjA3MDMzNjUyMX0.xIg4jPBvxPzGrxlyCh1JbMfXK-c2Ww5qFcLdUWIsi1A"
